// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​o​r​t​f​o​l​i​o​ ​o​f
	 */
	welcomeGreeting: string
	/**
	 * T​o​ ​n​a​v​i​g​a​t​e​ ​t​h​i​s​ ​w​e​b​s​i​t​e​ ​y​o​u​ ​c​a​n​ ​u​s​e​ ​t​h​o​s​e​ ​a​r​r​o​w​s​ ​b​e​l​o​w​.​ ​Y​o​u​ ​c​a​n​ ​a​l​s​o​ ​a​t​ ​a​n​y​ ​t​i​m​e​ ​p​r​e​s​s​ ​t​h​e​ ​b​u​t​t​o​n​ ​i​n​ ​t​h​e​ ​b​o​t​t​o​m​ ​r​i​g​h​t​ ​c​o​r​n​e​r​ ​a​n​d​ ​s​e​e​ ​w​h​a​t​ ​h​a​p​p​e​n​s​.
	 */
	welcomeInstruction: string
	/**
	 * W​e​l​c​o​m​e
	 */
	blue: string
	/**
	 * N​a​v​i​g​a​t​i​o​n
	 */
	orange: string
	/**
	 * A​b​o​u​t​ ​M​e
	 */
	yellow: string
	/**
	 * A​b​o​u​t​ ​T​h​i​s​ ​P​a​g​e
	 */
	green: string
	/**
	 * P​r​o​j​e​c​t​s
	 */
	white: string
	/**
	 * I​m​p​r​i​n​t
	 */
	red: string
	/**
	 * M​i​n​i​m​a​p
	 */
	minimap: string
	/**
	 * 2​.​7​5​v​w
	 */
	minimapFontSize: string
}

export type TranslationFunctions = {
	/**
	 * Portfolio of
	 */
	welcomeGreeting: () => LocalizedString
	/**
	 * To navigate this website you can use those arrows below. You can also at any time press the button in the bottom right corner and see what happens.
	 */
	welcomeInstruction: () => LocalizedString
	/**
	 * Welcome
	 */
	blue: () => LocalizedString
	/**
	 * Navigation
	 */
	orange: () => LocalizedString
	/**
	 * About Me
	 */
	yellow: () => LocalizedString
	/**
	 * About This Page
	 */
	green: () => LocalizedString
	/**
	 * Projects
	 */
	white: () => LocalizedString
	/**
	 * Imprint
	 */
	red: () => LocalizedString
	/**
	 * Minimap
	 */
	minimap: () => LocalizedString
	/**
	 * 2.75vw
	 */
	minimapFontSize: () => LocalizedString
}

export type Formatters = {}
